/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_qinkl_JNITest */

#ifndef _Included_com_qinkl_JNITest
#define _Included_com_qinkl_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qinkl_JNITest
 * Method:    jniGet
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_qinkl_JNITest_jniGet
  (JNIEnv *, jobject);

/*
 * Class:     com_qinkl_JNITest
 * Method:    jniSet
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_qinkl_JNITest_jniSet
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
